modLoader="javafml"
loaderVersion="[47,)"
license="MIT License https://github.com/McJtyMods/XNet/blob/1.16/LICENCE"
issueTrackerURL="http://github.com/McJtyMods/XNet/issues"
displayURL="http://github.com/McJtyMods/XNet/"
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="McJty"

[[mods]]
modId="xnet"
version="${file.jarVersion}"
displayName="XNet"
#updateJSONURL="http://myurl.me/" #optional
description='''
Powerful item/fluid/energy transfer
'''
[[dependencies.xnet]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.xnet]]
    modId="mcjtylib"
    mandatory=true
    versionRange="[1.20-8.0.4,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.xnet]]
    modId="rftoolsbase"
    mandatory=true
    versionRange="[1.20-5.0.4,)"
    ordering="AFTER"
    side="BOTH"
